version: "3.9"
services:

  server:
    image: shopper
    container_name: ${SERVER_HOST}
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - server-shopper-node-modules:/server/node_modules
      - ./server/leo.json:/server/leo.json
    depends_on:
      database:
        condition: service_healthy

  database:
    image: databaseshopper
    container_name: ${POSTGRES_HOST}
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - database-shopper:/var/lib/postgresql/data
    #command: "-p ${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 0s
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  server-shopper-node-modules:
    name: "server-shopper-node-modules"
  database-shopper:
    name: "database-shopper"